services:
  - type: web
    name: pulse-chatapp
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRES
        value: 15m
      - key: JWT_REFRESH_EXPIRES
        value: 7d
      - key: CLIENT_URL
        sync: false
